### PR TITLE
Attempt to fix clang compilation issue.

### PR DESCRIPTION
**Pull request by S-Dafarra**
Related issue: https://github.com/robotology/robotology-superbuild/issues/1108

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Review by Nicogene — APPROVED** [review]
If I remember correctly we substituted the brew CI with the conda one then I am afraid it is not tested by the CI, if you tested on your machine LGTM!

**Comment by S-Dafarra** [comment]
> If I remember correctly we substituted the brew CI with the conda one then I am afraid it is not tested by the CI, if you tested on your machine LGTM!

It is just an attempt considering the error of https://github.com/robotology/robotology-superbuild/issues/1108. I just tested it on Ubuntu. Plus the CI is not complaining, so I guess that it does not harm in any way :relaxed:

**Comment by traversaro** [comment]
I triggered the build in https://github.com/robotology/robotology-superbuild/runs/6269983296?check_suite_focus=true .

**Comment by traversaro** [comment]
> I triggered the build in https://github.com/robotology/robotology-superbuild/runs/6269983296?check_suite_focus=true .

The build was successful, so I guess the PR fix was useful.

**Pull request merged**
